services:
  - type: web
    name: netflix-cookie-checker-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: AUTHORIZED_USERS
        sync: false
      - key: ADMIN_USERS
        sync: false
      - key: WEBHOOK_URL
        sync: false 